### PR TITLE
0.6.6.6 + TP1.0230

### PR DESCRIPTION
**Pull request by rgleason**
Lennart, I updated your PI to TP1.0.230  and built it locally for Windows O5.7.1 and it works OK.
The font sizes have to be fixed for high DPI displays and I could not find the settings for some of the fonts used.
We have this problem with dashboard_tactics and tactics too, which I am in the process of trying to resolve.

You might not want to merge this with your "master" branch, but should make a new branch "update" and see if it builds ok. See suggestions how to do this below.

Note: I had to add the libs/tinyxml to get it to work with Windows.  There may very likely be other lib that are needed for the other builds (such as gl and GLU found in jon's testplugin/libs/) I was hoping to see how many of the builds actually compliled with this commit to my repos, but it is not setup to build. 

You will need to make a new branch   git checkout -b update  locally and then push it up to your remote. Then just make a new PR using the github webpage tools   back to your new update branch from mine.  I think you would start with this https://github.com/LennartG-Sve/GPS-Odometer_pi/pulls  after you pushed your new branch "update" up to your remote repository.

GPS-Odometer-0666

I see now that it is trying to build and is not finding the right cloudsmith api key so it fails. If you merge this PR into an new "update" branch it should have the right cloudsmith key and thus start building.

### CODE REVIEW

**Comment by rgleason** [comment]
Looking at the results, I think many of the builds succeeded but failed to upload to cloudsmith because of the key!

**Comment by LennartG-Sve** [comment]
Rick,
Thanks for your effort, it seems that ENV is the key to the local compile problem. 
I will download your updates and compare (diff) to what I have as I've also added socketCAN functionality to my local version.  Also: Had no idea about the character sizing problem, nor can I test it on my equipment. 
Give me a day or two first. If I get it working I'll upload as a beta.

**Comment by LennartG-Sve** [comment]
Rick, just FYI:
Changing 'cmake ..' to 'cmake .. -DWX_VER=30 -DBUILD_GTK3=true' did the trick:
Now I can compile!

**Comment by rgleason** [comment]
Great move. That is exactly right. Jon had mentioned this to me, following the appveyer.yml model.   Lennart will you add that "instruction" under issues so we update accordingly?

**Comment by rgleason** [comment]
Dear Lennart
I have been using jg tp1.0.230 with good success. Upgrading all to that. Have been traveling. Rick

**Comment by rgleason** [comment]
Fine, glad it worked out,  also glad to be of help.

**Comment by LennartG-Sve** [comment]
Rick, 
updated GPS Odometer with socketCAN functionality into version 0.7.0.0 and uploaded to beta. 
All but 'build-flatpak-arm64' and windows (using Visual Studio 2017!) built. I'm sure I've failed somewhere.
-----------------------------
Flatpack gave:

+ '[' stable = beta ']'
+ flatpak install --user -y flathub org.freedesktop.Sdk//20.08
error: Nothing matches org.freedesktop.Sdk in remote flathub
Exited with code exit status 1
CircleCI received exit code 1
---------------------------
Windows gave:
:\Program Files\Git\usr\bin;C:\Program Files\Meson\;C:\ProgramData\chocolatey\bin;C:\Program Files\Amazon\AWSCLI\;C:\Program Files (x86)\Yarn\bin\;C:\Users\appveyor\AppData\Local\Microsoft\WindowsApps;C:\Users\appveyor\.dotnet\tools;C:\Users\appveyor\AppData\Roaming\npm;C:\Users\appveyor\AppData\Local\Yarn\bin;C:\Program Files\AppVeyor\BuildAgent\
cd c:\project\ocpn_project
cd buildwin
The system cannot find the path specified.
Command exited with code 1
-------------------------
I will next  see if I can upload it to my live system on xubuntu 22.04.
Slowly getting there.

**Comment by LennartG-Sve** [comment]
Rick,
Installed the imported the tarball from cloudsmith, it did not (yet?) show in Beta. The tarball installed without errors but:
- It does not allow me to open Preferences (grayed out)
- It displays the jigsaw piece, not the proper image. 
- No errors, nothing but the plugin listed with options 'Website'. 
- The options 'Reinstall' and 'Uninstall' showed the first times but was the gone.

I'll check and compare, maybe the blind hen can find something.

**Comment by LennartG-Sve** [comment]
Rick,
I concentrated on the ubuntu 22.04 (jammy) problem, have no Windows system. Looks like the opencpn log is indicating missing libraries (if I read it correct) and eventually one or more missing files.
The attached file are snippets showing interesting parts in three sections. Have not translated the OS messages, it should still be quite clear.
The system is not stripped but a standard installation so O should be able to handle the installation properly
./media/lennart/Marine/GPS-Odometer load error.txt.zip

**Comment by LennartG-Sve** [comment]
Found the 'missing file' on the system:
root@Xubuntu-20:~# find / -name "libwx_baseu-3.0.so.0" -print
/usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0

It is apparently not where O expect it in some shared library, unclear where.

**Comment by rgleason** [comment]
That looks like a widgets file.   
Xubuntu-20:   ?   I thought you were using Ubuntu

**Comment by LennartG-Sve** [comment]
Rick, 
a/ It sure looks like a wxWidgets file not found.
b/ Xubuntu is a Ubuntu with a different GUI requiring less resources, most of the bling-bling is gone. They are however, in this respect, fully compatible. The locally compiled version also works just fine.

Continued tests revealed what might be the problem, suddenly it complained that the plugin was not compatible and it appears that 'libwx_baseu-3.2.so.0' is required, not 3.0.
I will try to upgrade and see what happens.

**Comment by LennartG-Sve** [comment]
Rick,
as the plugin said it required  "libwx_baseu-3.2.so.0" I upgraded the machine with wxwidgets 3.2, OpenCPN now reports 'wxWidgets version: wxWidgets 3.2.1 Linux 64 bit wxGTK'.
Now after reloading the plugin it says: 'Plugin ... depends on "libwx_baseu-3.0.so.0" but the main module was built for "libwx_baseu-3.2.so.0" '.
What is the 'main module'? Is that OpenCPN?

This wxWidget stuff is a mess. Is 3.0 or 3.2 the correct version and how should a regular user be able to handle it? Both versions are available but should never be installed at the same time.

**Comment by rgleason** [comment]
Lennart, I think I can help you with this.  We are using multiple versions of wxWidgets for various OS and various Opencpn versions.
It is complicated.
I have tried to build and accurate Template Table. I hope it helps.
https://github.com/jongough/testplugin_pi/issues/284

**Comment by LennartG-Sve** [comment]
Rick,
ubuntu 22.04 jammy is exactly what I'm fighting with!
1/ The template says wx32 and gtk3. My default installation had wx30, both ubuntu and xubuntu.
2/ Generated versions for both wx30 and wx32, both installs successfully but once installed both crashes OpenCPN without even an error message. Last log line says 'Loading Plugin .....'
3/ Note 3 says 'ubuntu-wx32-x86_64-22.04, special case for jammy'
4/ Also note that this is for TP 223, not fully updated,
I will do my next tests on Ubuntu 20.04 and drop 22.04 for the time being.

**Comment by rgleason** [comment]
Lennart we need bdbcat's advice here. It is beyond my knowledge. Can you post an issue in opencpn/plugins?

**Comment by LennartG-Sve** [comment]
Rick, this is also far beyond me but as jongough has indicated ubuntu 22.04 as a 'special case' (at least on 223) I feel it better to let him update whatever he need to do first, not running multiple tracks. This until jongough indicates otherwise.

The better news is: Running 20.04 seems at least to work ok, both with local compile (WX_VER 30 given) and thru github (no WX_VER given).

**Comment by rgleason** [comment]
Lennart, I am wondering if the TP template for ubuntu 22.04 jammy  needs some error fixed?   Have you tried other plugins that use TP 1.0.230  such as Weatherfax, Weather_routing, Cel_nav etc.?  I wonder if they are working properly.

**Comment by LennartG-Sve** [comment]
Rick, I'm pretty sure there is a problem with the  ubuntu 22.04 jammy configuration as it crashes OpenCPN when the same setup (only different .circleci) works on 20.04. As you know I'm using a limited set of the TP configuration and hence I have not tested with other plugins.

Wonder how my current odometer version (0.7.0.0) can be extended with the full TP set, if it is even possible or desirable. It seems at least not required as 20.04 works ok.

**Comment by rgleason** [comment]
Well it would be instructive if you were to test another TP plugin on that OS.  If it also fails, we might be able to consider that there may be something wrong about TP for that OS.

**Comment by rgleason** [comment]
As you know, we did test (requiring almost a month for all of it to get done, (bdbcat did a lot of the builds)  for all built OS in version TP 1.0.226

**Comment by LennartG-Sve** [comment]
Rick, sorry I misunderstood you. I will try to test some available plugins on 22.04, will check tomorrow.

**Comment by LennartG-Sve** [comment]
Rick, results from the ubuntu 22.04 plugin test, master catalogue:
1/ Standard plugins (GRIB, Chart Downloader, Dashboard 1.2 and WMM 1.1), already installed on my system, ok.
2/ o-charts 1.0.34 already installed on my system, ok
3/ From master catalogue: Celestial navigation, Climatology, Dashboard Tactics, Findit, GPS Odometer, Javascript, NMEA Converter, OCPN Draw, Plots, Polar, Pypilot, S63, Testplugin (230):, Watchdog and Weatherfax (all available)
4/ From beta catalogue: Dashboard Tactics, OCPN Draw, Tactics (all available)

All of the plugins listed under 3/ and 4/ gives the same result: Installs ok but message is then 'Plugin is not compatible with this version of OpenCPN, and will be uninstalled'. 

5/ Checking opencpn.log shows that all of the failed plugins share the same error message:
plugin <name> depends on library "libwx-baseu-3.0.so.0", but the main module was built for "libwx-baseu-3.2.so.0"

Again we have the wx-version problem. 
My xubuntu 22.04 system is a standard installation, fully updated  using the standard procedures for linux. It also has both wx3.0 and wx3.2 fully and properly installed.

**Comment by rgleason** [comment]
Lennart, this is great information. Now we can ask bdbcat or Jon, about it.  It appears to me that the TP template does not create the right plugin.  To bad, not enough testers,  Very sorry.   I think this should become a new issue under https://github.com/jongough/testplugin_pi/issues,  can you use this and write it up?  Then we can alert bdbcat and jon about it too.

**Comment by LennartG-Sve** [comment]
Issue added as #299

**Pull request merged**
