### PR TITLE
Manual update

### PR DESCRIPTION
**Pull request by leamas**
This is merely a cleanup after working with Antora for some time. Simplify paths, use Antora defaults and ádd support for making a local build of the manual if need be.

Fix some links flagged by the linkchecker tasks running on the manual.

Here are also provisions for the Edit This Page link which will work if/when is PR is accepted and the corresponding changes are made in the central configuration

### CODE REVIEW

**Comment by leamas** [comment]
Rebased: Removed dokuwiki cruft in last patch

**Comment by rgleason** [comment]
Dear Lennart,

After merging Alec's Pull Request, would you mind doing the following:

manual/site.yml

site:
  title: Odometer Plugin Manual    ---> to  title: Odometer

and manual/antora.yml

name: odometer
title: odometer     ---> change to  title: Odometer

These changes fix the index and nav.doc for the Plugins Manual.

Thanks. Rick

**Comment by leamas** [comment]
@lennart: Tack :)

**Comment by leamas** [comment]
The overall manual's part on GPS-Odometer is now built using the sources in this repository. This means that:

  - If you want to modify the overall manual it's just about editing the sources in the _manual_ directory and pushing them to github.
  - Users which wants updates to the manual might use the Edit This Page link in the manual.  Eventually, this will create a PR against your repo here, so you will then need to review and reject or merge the PR.

**Pull request merged**
